### ISSUE TITLE
No default theme when installing a site on Stack

### ISSUE THREAD

**Issue by vasiioandre** [presslabs/stack#55]
**What happened**:
When you install the Presslabs Stack on Minikube and create a site, there is no default WordPress theme available and an error message appears: `ERROR: The theme directory "twentynineteen" does not exist.`.

![screenshot 4](https://user-images.githubusercontent.com/30148945/63846610-d0fb8c80-c994-11e9-904e-cb13134f880a.png)

**What you expected to happen**:
The "twentynineteen" theme to be available as a default.

**How to reproduce it (as minimally and precisely as possible)**:

- Install Stack on Minikube
- Deploy a site with [these commands](https://www.presslabs.com/docs/stack/how-to/deploy-wordpress-on-stack/#getting-started)
- Install a site and go to the WordPress Themes section

**Comment by Margretor** [comment]
Still happens using the documentation from https://www.presslabs.com/docs/stack/how-to/deploy-wordpress-on-stack/#getting-started.
Using:
`wp theme install twentysixteen --activate` it seems usable. Maybe this can be used to debug by using find and see where is the actual theme folder or the permissions that are set by default.
