### ISSUE TITLE
Guide needs to be updated to use Helm 3

### ISSUE THREAD

**Issue by paulisio** [presslabs/stack#85]
**What happened**: Guide at https://www.presslabs.com/docs/stack/quickstarts/install-stack-on-gke/ needs to be updated to reflect Helm 3. All Helm 2 configs/commands need to be altered to reflect Helm 3 

**What you expected to happen**: have up to date docs on using stack with Helm 3

**How to reproduce it (as minimally and precisely as possible)**: install Helm 3 and try following the guide

**Anything else?**: It's been more than half a year since Helm 3 is released, https://helm.sh/blog/helm-3-released/

**Comment by edbergavera** [comment]
With Helm 3, I got the ff. error:

`➜  ~ kubectl apply -f https://raw.githubusercontent.com/presslabs/stack/master/deploy/manifests/00-crds.yaml
customresourcedefinition.apiextensions.k8s.io/wordpresses.wordpress.presslabs.org configured
customresourcedefinition.apiextensions.k8s.io/mysqlclusters.mysql.presslabs.org configured
customresourcedefinition.apiextensions.k8s.io/mysqlbackups.mysql.presslabs.org configured
error: error validating "https://raw.githubusercontent.com/presslabs/stack/master/deploy/manifests/00-crds.yaml": error validating data: ValidationError(CustomResourceDefinition.spec): unknown field "preserveUnknownFields" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceDefinitionSpec; if you choose to ignore these errors, turn validation off with --validate=false`

**Comment by edbergavera** [comment]
Well, I actually tried with `--validate=true` to see how it goes.

`kubectl apply --validate=false -f https://raw.githubusercontent.com/presslabs/stack/master/deploy/manifests/00-crds.yaml`

But got an error and couldn't proceed on the next step:

`➜  ~ helm upgrade -i stack presslabs/stack --namespace presslabs-system -f https://raw.githubusercontent.com/presslabs/stack/master/presets/gke.yaml

Release "stack" does not exist. Installing it now.
coalesce.go:199: warning: destination for resources is a table. Ignoring non-table value <nil>
coalesce.go:199: warning: destination for resources is a table. Ignoring non-table value <nil>
coalesce.go:199: warning: destination for resources is a table. Ignoring non-table value <nil>
coalesce.go:199: warning: destination for resources is a table. Ignoring non-table value <nil>
coalesce.go:199: warning: destination for resources is a table. Ignoring non-table value <nil>
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Application" in version "app.k8s.io/v1beta1"`

I think I have to go back with Helm 2.
