### ISSUE TITLE
Kubernetes node labels should not include kubernetes.io namespace in terraform scripts

### ISSUE THREAD

**Issue by paulisio** [presslabs/stack#86]
**What happened**: terraform scripts don't work with current GKE due to https://github.com/terraform-providers/terraform-provider-google/issues/6003 One can't use terraform scripts anymore to spin-up nodes due to using node-role.kubernetes.io namespace in configs. A workaround is to comment setting labels and then apply them manually via kubectl but perhaps this is not a proper thing to do.

**What you expected to happen**: proper namespace is used and updated across repo

**How to reproduce it (as minimally and precisely as possible)**: just try current terraform scripts on GKE, you will get an error about setting labels for nodes

**Anything else?**: perhaps having CI for "demo" project would help to catch this?

**Comment by paulisio** [comment]
module.stack.google_container_node_pool.database: Creating...
module.stack.google_container_node_pool.system: Creating...
module.stack.google_container_node_pool.wordpress: Creating...

Error: error creating NodePool: googleapi: Error 400: Applying kubernetes label is not allowed: node-role.kubernetes.io/presslabs-sys., badRequest

  on ../../modules/gke/main.tf line 53, in resource "google_container_node_pool" "system":
  53: resource "google_container_node_pool" "system" {



Error: error creating NodePool: googleapi: Error 400: Applying kubernetes label is not allowed: node-role.kubernetes.io/database,applying kubernetes label is not allowed: node-role.kubernetes.io/memcached,applying kubernetes label is not allowed: node-role.kubernetes.io/mysql., badRequest

  on ../../modules/gke/main.tf line 102, in resource "google_container_node_pool" "database":
 102: resource "google_container_node_pool" "database" {



Error: error creating NodePool: googleapi: Error 400: Applying kubernetes label is not allowed: node-role.kubernetes.io/wordpress., badRequest

  on ../../modules/gke/main.tf line 147, in resource "google_container_node_pool" "wordpress":
 147: resource "google_container_node_pool" "wordpress" {

**Comment by hacktarus** [comment]
Hello,
i had the same issue, i just replaced kubernetes.io by presslabs.com in label section in main.tf
it worked but there are other warnings.
an update of this file should be done

**Comment by paulbsch** [comment]
I created a GKE feature request to allow node-role.kubernetes.io labels over on the Google issue tracker.  Up vote and/or add your two cents if you would like to see this implemented:
https://issuetracker.google.com/issues/157973836

**Comment by bogdanpetrea** [comment]
Fixed by https://github.com/presslabs/stack/commit/9cdc97c7e794978b096b5037f092cd2f3ad834a5
