### ISSUE TITLE
Pods are stuck at Pending status

### ISSUE THREAD

**Issue by engmsaleh** [presslabs/stack#89]
**What happened**:
After the deployment using Helm is completed, Pods are stuck at pending status forever
 
**What you expected to happen**:
Pods are expected to running status, not pending

**How to reproduce it (as minimally and precisely as possible)**:
Deploy using Helm 

**Anything else?**:
I have found a solution for the problem by adding the `node-role.kubernetes.io/presslabs-sys=` to each node manually in Kubernetes using the following
`kubectl label <NodeName> node-role.kubernetes.io/presslabs-sys=`

**Comment by AMecea** [comment]
Related to #86

**Comment by bogdanpetrea** [comment]
Fixed by https://github.com/presslabs/stack/commit/9cdc97c7e794978b096b5037f092cd2f3ad834a5
